name: Test

on:
  push:
    branches:
      - main
      - v*
    paths-ignore:
      - "**.md"
    tags:
      - "*"
  workflow_dispatch:

jobs:
  test:
    name: Test-Action
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: ShellCheck
        uses: ludeeus/action-shellcheck@master

      - name: Test Action with needs updating equals true
        id: test_needs_updating
        uses: ./
        with:
          base-image: index.docker.io/library/nginx:1.21.0
          image: ubuntu
          verbose: true
      - name: Get Test Output (needs updating)
        run: 'echo "Needs updating (should be true): ${{ steps.test_needs_updating.outputs.needs-updating }}"'
      - name: Check that it needs updating
        run: echo "Needs updating (as expected)"
        if: steps.test_needs_updating.outputs.needs-updating == 'true'
      - name: Should not run (needs updating should be true)
        run: echo "Does not need updating (unexpected)"; exit 1
        if: steps.test_needs_updating.outputs.needs-updating == 'false'

      - name: Test Action with needs updating equals false (Linux)
        id: test_does_not_need_updating_linux
        uses: ./
        with:
          base-image: nginx:1.21.0
          image: nginx/nginx-ingress:1.12.0
          verbose: true
      - name: Get Test Output (Linux)
        run: |
          echo "Needs updating (Linux): ${{ steps.test_does_not_need_updating_linux.outputs.needs-updating }}"
          if [ '${{ steps.test_does_not_need_updating_linux.outputs.needs-updating }}' != 'false' ]; then
              echo "Incorrect output."
              exit 1
          fi
      - name: Should not run (needs updating should be false - Linux)
        run: echo "Needs updating (unexpected)"; exit 1
        if: steps.test_does_not_need_updating_linux.outputs.needs-updating == 'true'

      - name: Test Action with needs updating equals true (linux/arm64)
        id: test_needs_updating_linux_arm64
        uses: ./
        with:
          base-image: index.docker.io/library/nginx:1.21.0
          image: ubuntu
          verbose: true
          os: linux
          arch: arm64
      - name: Get Test Output (needs updating)
        run: 'echo "Needs updating (should be true): ${{ steps.test_needs_updating_linux_arm64.outputs.needs-updating }}"'
      - name: Check that it needs updating
        run: echo "Needs updating (as expected)"
        if: steps.test_needs_updating_linux_arm64.outputs.needs-updating == 'true'
      - name: Should not run (needs updating should be true)
        run: echo "Does not need updating (unexpected)"; exit 1
        if: steps.test_needs_updating_linux_arm64.outputs.needs-updating == 'false'

      - name: Test Action with needs updating equals false (Windows)
        id: test_does_not_need_updating_windows
        uses: ./
        with:
          base-image: mcr.microsoft.com/windows/servercore:ltsc2022
          # mcr.microsoft.com/windows/servercore/iis:windowsservercore also supports different os versions, which this action doesn't
          image: mcr.microsoft.com/windows/servercore:ltsc2022-KB5034129
          verbose: true
          os: windows
      - name: Get Test Output (Windows)
        run: |
          echo "Needs updating (Windows): ${{ steps.test_does_not_need_updating_windows.outputs.needs-updating }}"
          if [ '${{ steps.test_does_not_need_updating_linux.outputs.needs-updating }}' != 'false' ]; then
              echo "Incorrect output."
              exit 1
          fi
      - name: Should not run (needs updating should be false - Windows)
        run: echo "Needs updating (unexpected)"; exit 1
        if: steps.test_does_not_need_updating_windows.outputs.needs-updating == 'true'
